# Generated by Django 3.2.6 on 2021-08-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_bicycle_helmet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helmet',
            name='helmet_description',
        ),
    ]
